services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - /c/Users/emirhanhosanli/ekofinbackup:/var/opt/mssql/ekofinbackup 
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "timeout", "1", "bash", "-c", "</dev/tcp/localhost/1433"]
        interval: 10s
        retries: 5
        start_period: 40s


  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  api:
    build:
      dockerfile: Dockerfile
    image: companyservice-api:latest
    container_name: testapp_api
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5000:80"
      - "5001:5001"
    restart: unless-stopped

volumes:
  mssql_data:
  redis_data:
